// CodingSheet.js

// Define the shared column structure
const sharedColumns = [
	{
	  name: 'problem',
	  header: 'PROBLEM',
	},
	{
	  name: 'youtube',
	  header: 'YOUTUBE',
	},
	{
	  name: 'practice',
	  header: 'PRACTICE',
	},
	{
	  name: 'difficulty',
	  header: 'DIFFICULTY',
	},
  ];
  
  // Define the CodingSheet structure, referencing the shared columns
  export const CodingSheet = [
{
	title: "Arrays",
	columns: sharedColumns,
	problems: [
	{
		problem: 'Set Matrix Zeros',
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=N0MgLvceX7M',
		practice: 'https://leetcode.com/problems/set-matrix-zeroes/description/',
		difficulty: 'Medium',
	},
	{
		problem: 'Pascals Triangle',
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=bR7mQgwQ_o8',
		practice: 'https://leetcode.com/problems/pascals-triangle/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Next Permutation',
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=JDOXKqF60RQ',
		practice: 'https://leetcode.com/problems/next-permutation/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: "Kadane's Algorithm",
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=AHZpyENo7k4',
		practice: 'https://leetcode.com/problems/maximum-subarray/description/',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
		{
		problem: "Sort an array of 0's, 1's and 2's",
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=tp8JIuCXBaU',
		practice: 'https://leetcode.com/problems/sort-colors/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Stock Buy and Sell',
		article: '/path/to/article',
		youtube: 'https://www.youtube.com/watch?v=excAOvwF_Wk',
		practice: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
	// Add more problems as needed
	],
},
{
	title: "Arrays Part-II",
	columns: sharedColumns,
	problems: [
	{
		problem: 'Rotate Matrix',
		article: '/path/to/article',
		youtube: 'https://youtu.be/Z0R2u6gd3GU',
		practice: 'https://leetcode.com/problems/rotate-image/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
	},
	{
		problem: 'Merge Overlapping Subintervals',
		article: '/path/to/article',
		youtube: 'https://youtu.be/IexN60k62jo',
		practice: 'https://leetcode.com/problems/merge-intervals/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Merge two sorted arrays without extra space',
		article: '/path/to/article',
		youtube: 'https://youtu.be/n7uwj04E0I4',
		practice: 'https://leetcode.com/problems/merge-sorted-array/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Find the duplicate in an array of N+1 integers',
		article: '/path/to/article',
		youtube: 'https://youtube.com',
		practice: '/path/to/practice',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Repeat and Missing Number',
		article: '/path/to/article',
		youtube: 'https://youtu.be/2D0D8HE6uak',
		practice: 'https://www.interviewbit.com/problems/repeat-and-missing-number-array/',
		note: '/path/to/note',
		difficulty: 'Hard',
		},
		{
		problem: 'Inversion of Array (Pre-req: Merge Sort)',
		article: '/path/to/article',
		youtube: 'https://youtu.be/AseUmwVNaoY',
		practice: 'https://www.naukri.com/code360/problems/count-inversions_615',
		note: '/path/to/note',
		difficulty: 'Hard',
		},
	// Add more problems as needed
	],
},
{
title:"Arrays Part-III",
columns: sharedColumns,
problems:[
	{
		problem: 'Search in a 2 D matrix',
		article: '/path/to/article',
		youtube: 'https://youtu.be/JXU4Akft7yk',
		practice: 'https://leetcode.com/problems/search-a-2d-matrix/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Pow(x, n)',
		article: '/path/to/article',
		youtube: 'https://youtu.be/l0YC3876qxg',
		practice: 'https://leetcode.com/problems/powx-n/description/',
		note: '/path/to/note',
		difficulty: 'Medium',
		},
		{
		problem: 'Majority Element (>n/2 times)',
		article: '/path/to/article',
		youtube: 'https://youtube.com',
		practice: '/path/to/practice',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
		{
		problem: 'Majority Element (n/3 times)',
		article: '/path/to/article',
		youtube: 'https://youtube.com',
		practice: '/path/to/practice',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
		{
		problem: 'Grid Unique Paths',
		article: '/path/to/article',
		youtube: 'https://youtube.com',
		practice: '/path/to/practice',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
		{
		problem: 'Reverse Pairs (Leetcode)',
		article: '/path/to/article',
		youtube: 'https://youtube.com',
		practice: '/path/to/practice',
		note: '/path/to/note',
		difficulty: 'Easy',
		},
]
},
{
title:"Arrays Part-IV",
columns: sharedColumns,
problems:[
{
	problem: '2Sum Problem',
	article: '/path/to/article',
	youtube: 'https://youtu.be/UXDSeD9mN-k',
	practice: 'https://leetcode.com/problems/two-sum/',
	note: '/path/to/note',
	difficulty: 'Medium',
	},
	{
	problem: '4-Sum Problem',
	article: '/path/to/article',
	youtube: 'https://youtu.be/eD95WRfh81c',
	practice: 'https://leetcode.com/problems/4sum/',
	note: '/path/to/note',
	difficulty: 'Hard',
	},
	{
	problem: 'Longest Consecutive Sequence',
	article: '/path/to/article',
	youtube: 'https://youtu.be/oO5uLE7EUlM',
	practice: '/path/to/practice',
	note: 'https://leetcode.com/problems/longest-consecutive-sequence/',
	difficulty: 'Medium',
	},
	{
	problem: 'Largest Subarray with K sum',
	article: '/path/to/article',
	youtube: 'https://www.youtube.com/watch?v=frf7qxiN2qU',
	practice: 'https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1',
	note: '/path/to/note',
	difficulty: 'Medium',
	},
	{
	problem: 'Count number of subarrays with given xor K',
	article: '/path/to/article',
	youtube: 'https://youtu.be/eZr-6p0B7ME',
	practice: 'https://www.interviewbit.com/problems/subarray-with-given-xor/',
	note: '/path/to/note',
	difficulty: 'Hard',
	},
	{
	problem: 'Reverse Pairs (Leetcode)',
	article: '/path/to/article',
	youtube: 'https://youtu.be/qtVh-XEpsJo',
	practice: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
	note: '/path/to/note',
	difficulty: 'Medium',
	},
]
},
	
	{
		title:"Linked List",
		columns: sharedColumns,
		problems:[
			{
				problem: 'Reverse a LinkedList',
				article: '/path/to/article',
				youtube: 'https://youtu.be/iRtLEoL-r-g',
				practice: 'https://leetcode.com/problems/middle-of-the-linked-list/',
				note: '/path/to/note',
				difficulty: 'Easy',
				},
				{
				problem: 'Find the middle of LinkedList',
				article: '/path/to/article',
				youtube: 'https://youtu.be/sGdwSH8RK-o',
				practice: 'https://leetcode.com/problems/middle-of-the-linked-list/',
				note: '/path/to/note',
				difficulty: 'Easy',
				},
				{
				problem: 'Add two numbers as LinkedList',
				article: '/path/to/article',
				youtube: 'https://youtu.be/LBVsXSMOIk4',
				practice: '/path/to/practice',
				note: 'https://leetcode.com/problems/add-two-numbers/',
				difficulty: 'Medium',
				},
				{
				problem: 'Merge two sorted Linked List (use method used in mergeSort)',
				article: '/path/to/article',
				youtube: 'https://youtu.be/Xb4slcp1U38',
				practice: 'https://leetcode.com/problems/merge-two-sorted-lists/',
				note: '/path/to/note',
				difficulty: ' ',
				},
				{
				problem: 'Remove N-th node from back of LinkedList',
				article: '/path/to/article',
				youtube: 'https://youtu.be/Lhu3MsXZy-Q',
				practice: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
				note: '/path/to/note',
				difficulty: 'Medium',
				},
				{
				problem: 'Delete a given Node when a node is given.(0(1) solution)',
				article: '/path/to/article',
				youtube: 'https://youtu.be/icnp4FJdZ_c',
				practice: 'https://leetcode.com/problems/delete-node-in-a-linked-list/',
				note: '/path/to/note',
				difficulty: 'Medium',
				},
		]
		},
		{
			title:"Linked List Part-II",
			columns: sharedColumns,
			problems:[
				{
					problem: 'Find intersection point of Y LinkedList',
					article: '/path/to/article',
					youtube: 'https://youtu.be/u4FWXfgS8jw',
					practice: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
					note: '/path/to/note',
					difficulty: 'Medium',
					},
					{
					problem: 'Detect a cycle in Linked List',
					article: '/path/to/article',
					youtube: 'https://youtu.be/354J83hX7RI',
					practice: 'https://leetcode.com/problems/linked-list-cycle/',
					note: '/path/to/note',
					difficulty: 'Medium',
					},
					{
					problem: 'Reverse a LinkedList in groups of size k.',
					article: '/path/to/article',
					youtube: 'https://youtu.be/Of0HPkk3JgI',
					practice: '/path/to/practice',
					note: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
					difficulty: 'Hard',
					},
					{
					problem: 'Check if a LinkedList is palindrome or not.',
					article: '/path/to/article',
					youtube: 'https://youtu.be/-DtNInqFUXs',
					practice: 'https://leetcode.com/problems/palindrome-linked-list/',
					note: '/path/to/note',
					difficulty: 'Medium',
					},
					{
					problem: 'Find the starting point of the Loop of LinkedList',
					article: '/path/to/article',
					youtube: 'https://youtu.be/QfbOhn0WZ88',
					practice: 'https://leetcode.com/problems/linked-list-cycle-ii/',
					note: '/path/to/note',
					difficulty: 'Medium',
					},
					{
					problem: 'Flattening of a LinkedList',
					article: '/path/to/article',
					youtube: 'https://youtu.be/ysytSSXpAI0',
					practice: 'https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1',
					note: '/path/to/note',
					difficulty: 'Hard',
					},
			]
			},
			{
				title:"Linked List and Arrays",
				columns: sharedColumns,
				problems:[
					{
						problem: 'Rotate a LinkedList',
						article: '/path/to/article',
						youtube: 'https://youtu.be/9VPm6nEbVPA',
						practice: 'https://leetcode.com/problems/rotate-list/description/',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
						{
						problem: 'Clone a Linked List with random and next pointer',
						article: '/path/to/article',
						youtube: 'https://youtu.be/q570bKdrnlw',
						practice: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
						note: '/path/to/note',
						difficulty: 'Hard',
						},
						{
						problem: '3 sum',
						article: '/path/to/article',
						youtube: 'https://youtu.be/DhFh8Kw7ymk',
						practice: '/path/to/practice',
						note: 'https://leetcode.com/problems/3sum/',
						difficulty: 'Medium',
						},
						{
						problem: 'Trapping Rainwater',
						article: '/path/to/article',
						youtube: 'https://youtu.be/1_5VuquLbXg',
						practice: 'https://leetcode.com/problems/trapping-rain-water/',
						note: '/path/to/note',
						difficulty: 'Hard',
						},
						{
						problem: 'Remove Duplicate from Sorted array',
						article: '/path/to/article',
						youtube: 'https://youtu.be/37E9ckMDdTk',
						practice: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
						note: '/path/to/note',
						difficulty: 'Easy',
						},
						{
						problem: 'Max consecutive ones',
						article: '/path/to/article',
						youtube: 'https://youtu.be/bYWLJb3vCWY',
						practice: 'https://leetcode.com/problems/max-consecutive-ones/',
						note: '/path/to/note',
						difficulty: 'Easy',
						},
				]
				},
			{
				title:"Greedy Algorithm",
				columns: sharedColumns,
				problems:[
					{
						problem: 'N meetings in one room',
						article: '/path/to/article',
						youtube: 'https://youtu.be/mKfhTotEguk',
						practice: 'https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
						{
						problem: 'Minimum number of platforms required for a railway',
						article: '/path/to/article',
						youtube: 'https://youtu.be/AsGzwR_FWok',
						practice: 'https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1#',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
						{
						problem: 'Job sequencing Problem',
						article: '/path/to/article',
						youtube: 'https://youtu.be/QbwltemZbRg',
						practice: 'https://leetcode.com/problems/longest-consecutive-sequence/',
						note: '',
						difficulty: 'Medium',
						},
						{
						problem: 'Fractional Knapsack Problem',
						article: '/path/to/article',
						youtube: 'https://youtu.be/1ibsQrnuEEg',
						practice: 'https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
						{
						problem: 'Greedy algorithm to find minimum number of coins',
						article: '/path/to/article',
						youtube: 'https://youtu.be/mVg9CfJvayM',
						practice: 'https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
						{
						problem: 'Assign Cookies',
						article: '/path/to/article',
						youtube: 'https://youtu.be/DIX2p7vb9co',
						practice: 'https://leetcode.com/problems/assign-cookies/',
						note: '/path/to/note',
						difficulty: 'Medium',
						},
				]
				},
				{
					title:"Recursion",
					columns: sharedColumns,
					problems:[
						{
							problem: 'Subset Sums',
							article: '/path/to/article',
							youtube: 'https://youtu.be/rYkfBRtMJr8',
							practice: 'https://practice.geeksforgeeks.org/problems/subset-sums2234/1',
							note: '/path/to/note',
							difficulty: 'Medium',
							},
							{
							problem: 'Subset-II',
							article: '/path/to/article',
							youtube: 'https://youtu.be/RIn3gOkbhQE',
							practice: 'https://leetcode.com/problems/subsets-ii/',
							note: '/path/to/note',
							difficulty: 'Medium',
							},
							{
							problem: 'Combination sum-1',
							article: '/path/to/article',
							youtube: 'https://youtu.be/OyZFFqQtu98',
							practice: '/path/to/practice',
							note: 'https://leetcode.com/problems/combination-sum/',
							difficulty: 'Medium',
							},
							{
							problem: 'Combination sum-2',
							article: '/path/to/article',
							youtube: 'https://youtu.be/G1fRTGRxXU8',
							practice: 'https://leetcode.com/problems/combination-sum-ii/',
							note: '/path/to/note',
							difficulty: 'Medium',
							},
							{
							problem: 'Palindrome Partitioning',
							article: '/path/to/article',
							youtube: 'https://youtu.be/WBgsABoClE0',
							practice: 'https://leetcode.com/problems/palindrome-partitioning/',
							note: '/path/to/note',
							difficulty: 'Medium',
							},
							{
							problem: 'K-th permutation Sequence',
							article: '/path/to/article',
							youtube: 'https://youtu.be/wT7gcXLYoao',
							practice: 'https://leetcode.com/problems/permutation-sequence/',
							note: '/path/to/note',
							difficulty: 'Hard',
							},
					]
					},
					{
						title:"Recursion and Backtracking",
						columns: sharedColumns,
						problems:[
							{
								problem: 'Print all permutations of a string/array',
								article: '/path/to/article',
								youtube: 'https://youtu.be/f2ic2Rsc9pU',
								practice: 'https://leetcode.com/problems/permutations/',
								note: '/path/to/note',
								difficulty: 'Medium',
								},
								{
								problem: 'N queens Problem',
								article: '/path/to/article',
								youtube: 'https://youtu.be/i05Ju7AftcM',
								practice: 'https://leetcode.com/problems/n-queens/',
								note: '/path/to/note',
								difficulty: 'Hard',
								},
								{
								problem: 'Sudoko Solver',
								article: '/path/to/article',
								youtube: 'https://youtu.be/FWAIf_EVUKE',
								practice: '/path/to/practice',
								note: 'https://leetcode.com/problems/sudoku-solver/',
								difficulty: 'Hard',
								},
								{
								problem: 'M Coloring Problem',
								article: '/path/to/article',
								youtube: 'https://youtu.be/wuVwUK25RfcE',
								practice: 'https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1#',
								note: '/path/to/note',
								difficulty: 'Hard',
								},
								{
								problem: 'Rat in a Maze',
								article: '/path/to/article',
								youtube: 'https://youtu.be/bLGZhJlt4y0',
								practice: 'https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1',
								note: '/path/to/note',
								difficulty: 'Hard',
								},
								{
								problem: 'Word Break (print all ways)',
								article: '/path/to/article',
								youtube: ' ',
								practice: 'https://www.naukri.com/code360/problems/983635?topList=striver-sde-sheet-problems',
								note: '/path/to/note',
								difficulty: 'Medium',
								},
						]
						},

	// Add more sections as needed
  ];
  